export const API_PATHS = {
  health: '/health',
  appPublic: {
    base: '/api/apps/public',
    publicSettingsById: (appId) => `/prod/public-settings/by-id/${appId}`,
  },
  auth: {
    me: '/auth/me',
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    uploadAvatar: '/auth/me/avatar',
    removeAvatar: '/auth/me/avatar',
    forgotPassword: '/auth/forgot-password',
    verifyResetToken: '/auth/reset-password/verify',
    resetPassword: '/auth/reset-password',
  },
  members: {
    list: '/members/',
    summary: '/members/summary',
    import: '/members/import',
    importJob: '/members/import/jobs',
    importJobStatus: (jobId) => `/members/import/jobs/${jobId}`,
    me: '/members/me',
    byId: (id) => `/members/${id}`,
    byCode: (code) => `/members/code/${code}`,
  },
  challans: {
    list: '/challans/',
    summary: '/challans/summary',
    collectionStats: '/challans/collection-stats',
    payableMonths: '/challans/payable-months',
    importHistory: '/challans/import/history',
    importHistoryJob: '/challans/import/history/jobs',
    importHistoryJobStatus: (jobId) => `/challans/import/history/jobs/${jobId}`,
    byId: (id) => `/challans/${id}`,
    byMember: (memberId) => `/challans/member/${memberId}`,
    uploadProof: (id) => `/challans/${id}/upload-proof`,
    approve: (id) => `/challans/${id}/approve`,
    reject: (id) => `/challans/${id}/reject`,
    revert: (id) => `/challans/${id}/revert`,
    bulkCreate: '/challans/bulk-create',
  },
  bulk: {
    pendingReview: '/admin/bulk-pending-review',
    byGroupId: (bulkGroupId) => `/admin/bulk/${bulkGroupId}`,
    approve: (bulkGroupId) => `/admin/bulk/${bulkGroupId}/approve`,
    reject: (bulkGroupId) => `/admin/bulk/${bulkGroupId}/reject`,
  },
  admin: {
    wipeData: '/admin/system/wipe',
    dashboardCharts: '/admin/dashboard/charts',
    settings: '/admin/settings',
    passwordResetRequests: '/admin/password-reset-requests',
    approvePasswordReset: (id) => `/admin/password-reset-requests/${id}/approve`,
    rejectPasswordReset: (id) => `/admin/password-reset-requests/${id}/reject`,
  },
  campaigns: {
    list: '/campaigns/',
    importPayments: '/campaigns/import/payments',
    importPaymentsJob: '/campaigns/import/payments/jobs',
    importPaymentsJobStatus: (jobId) => `/campaigns/import/payments/jobs/${jobId}`,
    byId: (id) => `/campaigns/${id}`,
  },
  notifications: {
    list: '/notifications/',
    feed: '/notifications/feed',
    stream: '/notifications/stream',
    pushPublicKey: '/notifications/push/public-key',
    pushSubscribe: '/notifications/push/subscribe',
    pushUnsubscribe: '/notifications/push/unsubscribe',
    sendWhatsApp: '/notifications/send-whatsapp',
    byId: (id) => `/notifications/${id}`,
    read: (id) => `/notifications/${id}/read`,
    patchRead: '/notifications/read',
    markAllRead: '/notifications/mark-all-read',
    unreadCount: '/notifications/unread/count',
    adminSent: '/notifications/admin/sent',
  },
  requests: {
    list: '/requests/',
    adminList: '/admin/requests/',
    byId: (id) => `/requests/${id}`,
    approve: (id) => `/requests/${id}/approve`,
    reject: (id) => `/requests/${id}/reject`,
  },
  invites: {
    list: '/invites/',
    pending: '/invites/pending',
    byId: (id) => `/invites/${id}`,
    validate: '/invites/validate',
  },
  files: {
    upload: '/files/upload',
    uploadAvatar: '/files/upload/avatar',
    deleteFile: '/files/delete',
  },
  auditLogs: {
    list: '/audit-logs/',
    byId: (id) => `/audit-logs/${id}`,
  },
  users: {
    list: '/users/',
    byId: (id) => `/users/${id}`,
  },
  fundUtilizations: {
    list: '/fund-utilizations/',
    summary: '/fund-utilizations/summary',
    byId: (id) => `/fund-utilizations/${id}`,
  },
};
